routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/contact', 'ContactController@create');


Route::prefix('admin')->middleware('auth')->group(function() {
    Route::get('menu/parents', 'Admin\MenuItemController@getParents');
    Route::resource('menu-items', 'Admin\MenuItemController');
    Route::resource('pages', 'Admin\PageController');
});
Route::resource('admin', 'Admin\IndexController')->middleware('auth');

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
Route::get('/{slug?}', 'PageController@show')->where('slug', '[a-zA-Z-_0-9]+');
//Route::get('/', 'PageController@index');

//Route::resource('/api/menu', 'MenuController');
Route::get('/api/menu/{slug}', 'MenuController@show');

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $guarded = [];

    public function menuItems() {
        return $this->hasMany(MenuItem::class);
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Menu;
use App\Repositories\Menu\Contracts\MenuRepositoryInterface;
use Illuminate\Http\Request;

class MenuController extends Controller
{
    private $menuRepository;

    public function __construct(MenuRepositoryInterface $menuRepository) {
        $this->menuRepository = $menuRepository;
    }

    public function index() {
    }

    public function show($param) {
        return response()->json($this->menuRepository->getByTitle($param));
    }
}

resources/views/admin/menu/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Menu - Create</h1>
    </div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <menu-create></menu-create>
    </div>
@endsection

@section('javascript')
    {{--<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>--}}
    {{--<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>--}}
@endsection

resources/views/admin/menu/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Menu</h1>
    </div>
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <a href="{{route('menu-items.create')}}">Create new menu-item</a>
    </div>
@endsection

@section('javascript')
    {{--<script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>--}}
    {{--<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>--}}
@endsection